# ??????????????MySQL???????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/account_book?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=root

# MyBatis??
mybatis.type-aliases-package=com.example.accountbook.entity
mybatis.mapper-locations=classpath:mapper/*.xml

# ??????8080??????
server.port=8080

# ??Bean???????MyBatis?Spring Boot????
spring.main.allow-bean-definition-overriding=true